name: eventlog-ci
on: [push]
jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: eventlog

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: cmake "..\eventlog"

      - name: Build
        working-directory: build
        run: |
          cmake --build .
